apiVersion: v1
kind: Service
metadata:
  name: tasksbackendservice
spec:
  selector:
    app: tasksbackendlabel
  type: LoadBalancer
  ports:
    - name: tasksbackendport
      port: 9000
      targetPort: 9000
  externalIPs:
    - 192.168.64.3
